package com.example.core.utils

const val TAB_SELECTOR_ANIMATION_DURATION = 300

const val AMOUNT_OF_PER_PAGE_FEATURED_COLLECTIONS = 7

const val BASE_URL = "https://api.pexels.com/v1/"

const val AMOUNT_OF_PER_PAGE_PHOTOS = 30

const val PREFETCH_DISTANCE_PHOTO = 1

const val PREFETCH_DISTANCE_FEATURED_COLLECTIONS = 3

const val SEARCH_DEBOUNCE_DELAY = 500L

const val FIRST_SELECTED_INDEX = 1

const val NO_ONE_FEATURED_COLLECTION_SELECTED = -1






